[2025-10-10T16:01:08.905+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-10T16:01:09.024+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_quality.soda_test_core manual__2025-10-10T16:00:56.506598+00:00 [queued]>
[2025-10-10T16:01:09.060+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_quality.soda_test_core manual__2025-10-10T16:00:56.506598+00:00 [queued]>
[2025-10-10T16:01:09.061+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-10T16:01:09.107+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): soda_test_core> on 2025-10-10 16:00:56.506598+00:00
[2025-10-10T16:01:09.117+0000] {standard_task_runner.py:63} INFO - Started process 115 to run task
[2025-10-10T16:01:09.128+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_quality', 'soda_test_core', 'manual__2025-10-10T16:00:56.506598+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp7fnkyqha']
[2025-10-10T16:01:09.131+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask soda_test_core
[2025-10-10T16:01:09.323+0000] {task_command.py:426} INFO - Running <TaskInstance: data_quality.soda_test_core manual__2025-10-10T16:00:56.506598+00:00 [running]> on host cc5471964322
[2025-10-10T16:01:09.530+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='data_quality' AIRFLOW_CTX_TASK_ID='soda_test_core' AIRFLOW_CTX_EXECUTION_DATE='2025-10-10T16:00:56.506598+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-10T16:00:56.506598+00:00'
[2025-10-10T16:01:09.538+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-10T16:01:09.542+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-10T16:01:09.546+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'soda scan -d pg_datasource -c /opt/airflow/include/soda/configuration.yml -v SCHEMA=core /opt/airflow/include/soda/checks.yml']
[2025-10-10T16:01:09.584+0000] {subprocess.py:86} INFO - Output:
[2025-10-10T16:01:11.853+0000] {subprocess.py:93} INFO - [16:01:11] Soda Core 3.3.14
[2025-10-10T16:01:12.032+0000] {subprocess.py:93} INFO - [16:01:12] Scan summary:
[2025-10-10T16:01:12.033+0000] {subprocess.py:93} INFO - [16:01:12] 4/4 checks PASSED:
[2025-10-10T16:01:12.034+0000] {subprocess.py:93} INFO - [16:01:12]     yt_api in pg_datasource
[2025-10-10T16:01:12.034+0000] {subprocess.py:93} INFO - [16:01:12]       Check for Like_Count greater than Video_Views [PASSED]
[2025-10-10T16:01:12.035+0000] {subprocess.py:93} INFO - [16:01:12]       Check for Comments_Count greater than Video_Views [PASSED]
[2025-10-10T16:01:12.036+0000] {subprocess.py:93} INFO - [16:01:12]       missing_count("Video_ID") = 0 [PASSED]
[2025-10-10T16:01:12.036+0000] {subprocess.py:93} INFO - [16:01:12]       duplicate_count("Video_ID") = 0 [PASSED]
[2025-10-10T16:01:12.037+0000] {subprocess.py:93} INFO - [16:01:12] All is good. No failures. No warnings. No errors.
[2025-10-10T16:01:12.773+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-10T16:01:12.774+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-10T16:01:12.806+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_quality, task_id=soda_test_core, run_id=manual__2025-10-10T16:00:56.506598+00:00, execution_date=20251010T160056, start_date=20251010T160109, end_date=20251010T160112
[2025-10-10T16:01:12.842+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-10T16:01:12.861+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-10T16:01:12.865+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
