[2025-10-13T04:31:55.358+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-13T04:31:55.454+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_quality.soda_test_core manual__2025-10-13T04:31:49.657546+00:00 [queued]>
[2025-10-13T04:31:55.480+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_quality.soda_test_core manual__2025-10-13T04:31:49.657546+00:00 [queued]>
[2025-10-13T04:31:55.485+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-13T04:31:55.535+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): soda_test_core> on 2025-10-13 04:31:49.657546+00:00
[2025-10-13T04:31:55.554+0000] {standard_task_runner.py:63} INFO - Started process 276 to run task
[2025-10-13T04:31:55.578+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_quality', 'soda_test_core', 'manual__2025-10-13T04:31:49.657546+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp9yflw0xe']
[2025-10-13T04:31:55.592+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask soda_test_core
[2025-10-13T04:31:56.086+0000] {task_command.py:426} INFO - Running <TaskInstance: data_quality.soda_test_core manual__2025-10-13T04:31:49.657546+00:00 [running]> on host 5c801f6c26b0
[2025-10-13T04:31:56.596+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='data_quality' AIRFLOW_CTX_TASK_ID='soda_test_core' AIRFLOW_CTX_EXECUTION_DATE='2025-10-13T04:31:49.657546+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-13T04:31:49.657546+00:00'
[2025-10-13T04:31:56.599+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-13T04:31:56.602+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-13T04:31:56.610+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'soda scan -d pg_datasource -c /opt/airflow/include/soda/configuration.yml -v SCHEMA=core /opt/airflow/include/soda/checks.yml']
[2025-10-13T04:31:56.639+0000] {subprocess.py:86} INFO - Output:
[2025-10-13T04:32:01.791+0000] {subprocess.py:93} INFO - [04:32:01] Soda Core 3.3.14
[2025-10-13T04:32:02.038+0000] {subprocess.py:93} INFO - [04:32:02] Scan summary:
[2025-10-13T04:32:02.041+0000] {subprocess.py:93} INFO - [04:32:02] 4/4 checks PASSED:
[2025-10-13T04:32:02.042+0000] {subprocess.py:93} INFO - [04:32:02]     yt_api in pg_datasource
[2025-10-13T04:32:02.044+0000] {subprocess.py:93} INFO - [04:32:02]       Check for Like_Count greater than Video_Views [PASSED]
[2025-10-13T04:32:02.045+0000] {subprocess.py:93} INFO - [04:32:02]       Check for Comments_Count greater than Video_Views [PASSED]
[2025-10-13T04:32:02.046+0000] {subprocess.py:93} INFO - [04:32:02]       missing_count("Video_ID") = 0 [PASSED]
[2025-10-13T04:32:02.046+0000] {subprocess.py:93} INFO - [04:32:02]       duplicate_count("Video_ID") = 0 [PASSED]
[2025-10-13T04:32:02.047+0000] {subprocess.py:93} INFO - [04:32:02] All is good. No failures. No warnings. No errors.
[2025-10-13T04:32:02.826+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-13T04:32:02.827+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-13T04:32:02.874+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_quality, task_id=soda_test_core, run_id=manual__2025-10-13T04:31:49.657546+00:00, execution_date=20251013T043149, start_date=20251013T043155, end_date=20251013T043202
[2025-10-13T04:32:02.932+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-13T04:32:02.956+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T04:32:02.960+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
